### ISSUE TITLE
Search results for "King Mackerel" are not formatted as desired

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/gomexsi-web#68]
As received from @jsimons9 
```
I just tried to do a search by common name and got no result. I did the search on king mackerel. One thought has occurred to me - I don't know how much work this will be, but I think it might be a good idea to either have one window for common names and one for scientific, or have a way for the user to indicate whether they are searching by common or scientfiic names. That way the drop down should only contain either common or scientific names.
```

**Comment by jhpoelen** [comment]
@jsimons9 are you planning to include this in this iteration of website developement? I think it might be a nice investment. Please note that GloBI has a bunch of spanish common names also, so we might be able to leverage that here.

**Comment by jsimons9** [comment]
Hi Jorrit,

Not sure what you are referring to by “this” – please clarify.

Jim

**Comment by jhpoelen** [comment]
When I review the history of this issue (i.e. https://github.com/GoMexSI/gomexsi-web/issues/68), I think that you'd like to have common names to appear along with scientific name in the drop down. That is what I meant by "this". Please confirm.

**Comment by jsimons9** [comment]
OK, I can see what I was getting at.  It is very likely that someone using common names is not going to have any idea what the scientific name is.  What I would like to see is the user have a choice of using common names or scientific names (like ITIS does) so there is no confusion.  I think mixing the scientific and common names in the same dropdown is a bad idea.  Can we create a selector on the query page so that the user can select the naming scheme they are most comfortable with??
One other option (though not my preferred) would be to include (in parentheses) the common name next to the scientific name.  This way the user learns both names.  And if there was a selector, then if common names were selected, the scientific name would appear in parentheses.  This method does have some merit as an educational perk.

**Comment by jhpoelen** [comment]
I've documented @jsimons9 option to include common names in the name suggestions (#97) to address this issue.

**Comment by jhpoelen** [comment]
@jsimons9 shared that this is not an issue.
