### ISSUE TITLE
Links to Fishbase

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#72]
We had some email discussions started on this but not where it left off.  This is something we have discussed with Fishbase folks for quite some time, so let me know if I need to do anything to make it happen. This link could appear below the EOL link now in place??

**Comment by Dengaloo** [comment]
Jorrit and Jim

1) there is the match names tool (FB: http://www.fishbase.ca/tools/upload/checkname.php; and and SLB: http://www.sealifebase.ca/Topic/List.php?group=match_names. This might be useful for this work. Note that SLB uses the WoRMS as its taxonomic backbone;

2) we can invite Nicolas Bailly to respond to this Catalog of Fishes to FishBase url pointing because he is the one who works with Bill Eschmeyer on this for FishBase.

**Comment by jhpoelen** [comment]
Hi @Dengaloo - Thanks for sharing the link to the name matching tool. I think this tool is great for one-time manual checks for a limited number of names. However, for our use case, I feel that continually and manually linking our names seems a bit inefficient.

The GoMexSI web already has an automated method to resolve names and detect unmatched/invalid names. Use this method, taxa provided by GoMexSI are automatically linked to NCBI, WoRMS, EOL, Open Tree of Life, etc.  Perhaps we can re-use that method. 

There's many ways to skin a cat, perhaps @jsimons9 has some ideas about this.

**Comment by jsimons9** [comment]
Hi to all,

  Well, I have not had a chance to take a look at the name matching tool as of yet.  It seems as though an automated method is a good approach.  I am curious as how the method used by GoMexSI resolves names when they do not agree in the different taxonomic databases??  I will try to have more comments later.

Jim

**Comment by jhpoelen** [comment]
Links to FishBase are now provided when available. See attached screenshot. 

![screenshot from 2017-11-15 11-39-42](https://user-images.githubusercontent.com/1084872/32856655-3c22e66c-c9fa-11e7-9fcc-f3553a0f2bfc.png)
