### ISSUE TITLE
enabled deep linking to specific query pages

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/gomexsi-web#95]
as discussed with @jsimons9 - 

Currently, the gomexsi query pages allow for querying by name. However, it is not possible to share a link to the query with somebody else.

Suggest to implement a method to allow easy sharing of query links for GoMexSI similar to a link to query for _Ariopsis felis_  http://www.globalbioticinteractions.org/?sourceTaxon=Ariopsis%20felis&interactionType=interactsWith in GloBI .

@reedhewitt suggest to discuss with Jim to see how this might be worked into ongoing efforts.

**Comment by reedhewitt** [comment]
As it happens, this has already been done in the development code I have on my local machine.  Some of the changes that I was making to the Exploration mode required that query parameters be in the URL instead of submitted via post like they were before.

As soon as Jim is ready for me to upload these changes (for the public launch of GoMexSI 2.0) then users will be able to take advantage of this.  Taxonomic queries, spatial queries, and Exploration mode all encode their parameters in the URL.

I'll go ahead and mark this as closed, since the work is done.

**Comment by jhpoelen** [comment]
@reedhewitt Would it be an idea to close issues only after they have been tested on the public site. This would help me, because now, I cannot see the difference between features that are available to users, and features that are not yet available to users. Curious to hear your ideas on this.

**Comment by reedhewitt** [comment]
@jhpoelen That is fine with me -- I'll leave this ticket open until the changes have been launched. I just emailed Jim to see if he is ready for me to deploy the changes I have been working on, so it may be pretty soon.

**Comment by jhpoelen** [comment]
As far as I can tell this feature has been implemented see #104 for example.
